# Multivariable Linear Regression

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
x_train = torch.FloatTensor([[73,80,75],
                            [93,88,93],
                            [89,91,90],
                            [96,98,100],
                            [73,66,70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

W = torch.zeros((3,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

hypothesis = x_train.matmul(W) + b

In [ ]:
class MultivariableLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)
        
    def forward(self, x):
        return self.linear(x)
    
hypothesis = model(x_train)

In [3]:
cost = torch.mean((hypothesis - y_train) ** 2)

In [ ]:
cost = F.mse_loss(prediction, y_train)

In [15]:
class Multivariable_Linear_Regression_Model(nn.Module):
    def __init__(self, input, output):
        super().__init__()
        self.linear = nn.Linear(input, output)
        
    def forward(self, x):
        return self.linear(x)


x_train = torch.FloatTensor([[73,80,75],
                            [93,88,93],
                            [89,91,90],
                            [96,98,100],
                            [73,66,70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

model = Multivariable_Linear_Regression_Model(3, 1)
optimizer = optim.SGD([W, b], lr = 0.1)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    hypothesis = model(x_train)
    cost = F.mse_loss(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()))

Epoch    0/20 hypothesis: tensor([12.5929, 17.4619, 15.9204, 17.9203, 13.5011]) Cost: 24529.964844
Epoch    1/20 hypothesis: tensor([12.5929, 17.4619, 15.9204, 17.9203, 13.5011]) Cost: 24529.964844
Epoch    2/20 hypothesis: tensor([12.5929, 17.4619, 15.9204, 17.9203, 13.5011]) Cost: 24529.964844
Epoch    3/20 hypothesis: tensor([12.5929, 17.4619, 15.9204, 17.9203, 13.5011]) Cost: 24529.964844
Epoch    4/20 hypothesis: tensor([12.5929, 17.4619, 15.9204, 17.9203, 13.5011]) Cost: 24529.964844
Epoch    5/20 hypothesis: tensor([12.5929, 17.4619, 15.9204, 17.9203, 13.5011]) Cost: 24529.964844
Epoch    6/20 hypothesis: tensor([12.5929, 17.4619, 15.9204, 17.9203, 13.5011]) Cost: 24529.964844
Epoch    7/20 hypothesis: tensor([12.5929, 17.4619, 15.9204, 17.9203, 13.5011]) Cost: 24529.964844
Epoch    8/20 hypothesis: tensor([12.5929, 17.4619, 15.9204, 17.9203, 13.5011]) Cost: 24529.964844
Epoch    9/20 hypothesis: tensor([12.5929, 17.4619, 15.9204, 17.9203, 13.5011]) Cost: 24529.964844
Epoch   10

# Logistic Regression

In [16]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

### seed

In [17]:
import random
random.seed(3)

In [36]:
random.seed(0)
random.random()
random.random()

0.7579544029403025

In [37]:
random.seed(0)
random.random()
random.random()

0.7579544029403025

In [38]:
random.seed(0)
random.random()

0.8444218515250481

In [39]:
random.randrange(0, 10)

6

In [40]:
random.randrange(0, 10)

0

In [41]:
random.randrange(0, 10)

4

In [42]:
random.randrange(0, 10)

8

In [53]:
torch.manual_seed(1)

In [62]:
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data) # 6 x 2
y_train = torch.FloatTensor(y_data) # 6 x 1

W = torch.zeros((2,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([W, b], lr = 1)
nb_epochs = 1000

for epoch in range(nb_epochs + 1):
    # hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)

    # losses = -(y_train[0] * torch.log(hypothesis[0]) + (1 - y_train[0]) * torch.log(1 - hypothesis[0]))
    # cost = losses.mean()
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031672
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852


### e

In [55]:
print('e^1 = ', torch.exp(torch.FloatTensor([1])))

e^1 =  tensor([2.7183])


In [59]:
print('1/(1+e^{-1}) = ', torch.sigmoid(torch.FloatTensor([1])))

1/(1+e^{-1}) =  tensor([0.7311])


In [71]:
# Evaluation
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis)

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward>)


In [75]:
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction.float())

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [74]:
print(y_train)

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [76]:
correct_prediction = prediction.float() == y_train
print(correct_prediction)

tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True]])


### Higher Implementation with class

In [96]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        return self.sigmoid(self.linear(x))
    
model = BinaryClassifier()
optimizer = optim.SGD(model.parameters(), lr = 1)

nb_epochs = 100
for epoch in range(nb_epochs + 1):
    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy: {:2.2f}'.format(epoch, nb_epochs, cost.item(), accuracy * 100))

Epoch    0/100 Cost: 0.574488 Accuracy: 83.33
Epoch   10/100 Cost: 0.498898 Accuracy: 66.67
Epoch   20/100 Cost: 0.472237 Accuracy: 66.67
Epoch   30/100 Cost: 0.396055 Accuracy: 83.33
Epoch   40/100 Cost: 0.336031 Accuracy: 83.33
Epoch   50/100 Cost: 0.283760 Accuracy: 83.33
Epoch   60/100 Cost: 0.236473 Accuracy: 100.00
Epoch   70/100 Cost: 0.194791 Accuracy: 100.00
Epoch   80/100 Cost: 0.164508 Accuracy: 100.00
Epoch   90/100 Cost: 0.148195 Accuracy: 100.00
Epoch  100/100 Cost: 0.137658 Accuracy: 100.00


# Softmax Classification

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
z = torch.FloatTensor([1, 2, 3])
hypothesis = F.softmax(z, dim = 0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])
